import argparse
import ast
from pathlib import Path

def parse_python_file(file_path):
    """
    Reads a Python file and extracts docstrings for the module, classes, and functions.
    """
    with open(file_path, 'r', encoding='utf-8') as f:
        try:
            tree = ast.parse(f.read())
            
            file_data = {
                "module_doc": ast.get_docstring(tree),
                "classes": {},
                "functions": {}
            }

            for node in tree.body:
                if isinstance(node, ast.ClassDef):
                    file_data["classes"][node.name] = ast.get_docstring(node)
                elif isinstance(node, ast.FunctionDef):
                    file_data["functions"][node.name] = ast.get_docstring(node)

            return file_data
            
        except Exception as e:
            print(f"❌ Error parsing {file_path.name}: {e}")
            return None

def scan_directory(directory_path):
    """
    Recursively finds all .py files and extracts their documentation structures.
    """
    path = Path(directory_path)
    
    if not path.exists() or not path.is_dir():
        print(f"❌ Error: '{directory_path}' is not a valid directory.")
        return None

    print(f"🔍 Scanning '{directory_path}'...\n")
    all_project_data = {}

    for py_file in path.rglob('*.py'):
        if any(ignore in py_file.parts for ignore in ['venv', '__pycache__', '.git']):
            continue
            
        print(f"📄 Analyzing: {py_file.name}")
        file_data = parse_python_file(py_file)
        
        if file_data:
            all_project_data[py_file.name] = file_data
            
    return all_project_data

def generate_markdown(project_data, output_file="README.md"):
    """
    Takes the extracted project data and formats it into a Markdown file.
    """
    if not project_data:
        print("⚠️ No data found to generate README.")
        return

    print(f"\n✍️  Writing documentation to {output_file}...")
    
    md_lines = [
        "# Project Documentation\n",
        "> *Autogenerated by Auto-README Generator.*\n\n",
        "---\n"
    ]
    
    # Loop through every file we scanned
    for file_name, data in project_data.items():
        md_lines.append(f"## 📁 File: `{file_name}`\n")
        
        # 1. Add Module Docstring
        if data["module_doc"]:
            # Clean up the formatting slightly
            clean_doc = data["module_doc"].strip()
            md_lines.append(f"{clean_doc}\n")
        else:
            md_lines.append("*No module-level description provided.*\n")
            
        # 2. Add Classes
        if data["classes"]:
            md_lines.append("### Classes\n")
            for cls_name, cls_doc in data["classes"].items():
                md_lines.append(f"- **`{cls_name}`**")
                if cls_doc:
                    # Format class docstrings as nested bullet points
                    md_lines.append(f"  - {cls_doc.strip().split(chr(10))[0]}") # Grabs just the first line
            md_lines.append("\n")
                
        # 3. Add Functions
        if data["functions"]:
            md_lines.append("### Functions\n")
            for func_name, func_doc in data["functions"].items():
                md_lines.append(f"- **`{func_name}()`**")
                if func_doc:
                    md_lines.append(f"  - {func_doc.strip().split(chr(10))[0]}")
            md_lines.append("\n")
            
        md_lines.append("---\n")
        
    # Write everything to the file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.writelines(line + "\n" for line in md_lines)
        
    print(f"✅ Success! Open {output_file} to see your generated docs.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Auto-README Generator: Scans a project and extracts docstrings.")
    parser.add_argument("target_dir", help="The path to the Python project directory you want to scan.")
    
    args = parser.parse_args()
    
    # 1. Scan the directory and get the data
    project_data = scan_directory(args.target_dir)
    
    # 2. Pass that data to the Markdown generator
    if project_data:
        generate_markdown(project_data)